version: '3.0'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins1
    volumes:
      - /data/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"

